export const COMPONENT_TYPE_CREDIT_FORM = {
  SUCCESS_COMPONENT: 'success',
  FAILURE_COMPONENT: 'failure',
  OTP_COMPONENT: 'otp',
  DEFAULT_COMPONENT: 'default',
  FORM_COMPONENT: '',
};

export const STATUS_ERROR = {
  FAIL_STATUS: 400,
  FAIL_BY_OVER_REQUEST_TIME: 401,
  UNKNOWN_ERR_STATUS: 500,
};
