export enum AuthCode {
  ACCOUNT_LOCKED = 'Authentication:00103',
  ACCOUNT_TEMPORARY_SUSPENDED = 'Authentication:00101',
}

export enum OMSCode {
  ORDER_CANCELLED_OR_FINISHED = 'OMSAPI:00401',
}

export enum CartCode {
  SESSION_NOT_FOUND = 'CART_CENTER:000500',
}

export enum OTPCode {
  REACHED_LIMIT = 'ERR-STOREFRONT:OTP:01429',
  WRONG_OTP_INPUT = 'ERR-STOREFRONT:OTP:01429:01430',
  HIT_LIMIT_SEND_OTP_1H = 'ERR-STOREFRONT:OTP:01434',
  HIT_LIMIT_SEND_OTP_24H = 'ERR-STOREFRONT:OTP:01431',
  HIT_LIMIT_SEND_OTP_4H = 'ERR-STOREFRONT:OTP:01432',
  HIT_LIMIT_SEND_OTP_2H = 'ERR-STOREFRONT:OTP:01433',
}

export enum TpBankCode {
  BUSY = 'ERR-STOREFRONT:TP_BANK:01528',
  NOTFOUND_ORDER_PAYMENT = 'ERR-STOREFRONT:TP-BANK:01529',
  REFUND_ACCOUNT_NOT_FOUND = 'ERR-STOREFRONT:TP-BANK:01530',
  REFUND_ACCOUNT_NOT_APPROVED = 'ERR-STOREFRONT:TP-BANK:01531',
  INVALID_ACCOUNT_NAME = 'ERR-STOREFRONT:TP-BANK:015206',
}
