export enum TpBankOverdraftLoanStatus {
  LOAN_PROCESS = 1,
  APPROVAL_RULE = 2,
  LOAN_REJECTED = 3,
  LOAN_DISBURSED = 4,
}

export enum BankAccountInfoStatus {
  SUBMITED_INFO_PENDING = 1,
  APPROVED_BANK_ACCOUNT = 2,
  REJECT_BANK_ACCOUNT = 3,
  BOOKED_ORDER_SUCCESS = 4,
}

export enum TpBankStatus {
  LOAN_PROCESS = 'TPBANK_LOAN_PROCESS',
  APPROVAL_RULE = 'TPBANK_APPROVAL_RULE',
  LOAN_REJECTED = 'TPBANK_LOAN_REJECTED',
  LOAN_DISBURSED = 'TPBANK_LOAN_DISBURSED',
}
